language: php

sudo: false

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - .phpunit
    - php-$MIN_PHP

services:
  - mongodb
  - memcached

matrix:
  include:
    - env: MONGO=2.6.5.5
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then echo extension = mongo.so >> $INI_FILE; fi;
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then echo extension = memcache.so >> $INI_FILE; fi;
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then (echo yes | pecl install -f apcu-4.0.10 && echo apc.enable_cli = 1 >> $INI_FILE) || echo "Let's continue without apcu extension"; fi;
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - php app/console orchestra:mongodb:fixtures:load --type=functional -e=test

script:
  - phpunit -c app/ --testsuite=unit
  - phpunit -c app/ --testsuite=functional
