language: php

services:
  - redis-server
  - mongodb

php:
  - 5.4

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update

install:
  - composer install
  - sudo apt-get install mongodb-org-server

before_script:
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - php app/console doc:mo:f:l -e=test

script: phpunit -c app/ --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=80da7fe449f831ae2940a4c6918f325bbcba1fd0888220b9ae0e3649284989e3 ./bin/test-reporter
