language: php

sudo: false

dist: precise

cache:
  directories:
    - ~/.composer/cache

services:
  - elasticsearch

matrix:
  include:
    - env: MONGOPHP=2.6.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - ghostscript
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - ghostscript
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise
    - env: MONGOPHP=2.6.7.0
      php: 7.0
      addons:
        apt:
          packages:
            - libav-tools
            - ghostscript
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.7.0
      php: 7.0
      addons:
        apt:
          packages:
            - libav-tools
            - ghostscript
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise

before_install:
  - printf "\n" |pecl install imagick
  - printf "\n" |pecl install mongodb
  - cp .travis.php_$(phpenv version-name).ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-dist

before_script:
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done

script:
  - ./bin/phpunit --testsuite=unit
  - ./bin/phpunit --testsuite=functional
