imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: log.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1.0.0
        #assets_version: SomeVersionScheme
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: %session_name%
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

braincrafted_bootstrap:
    auto_configure:
        assetic: false
        knp_menu: false
        knp_paginator: false
        twig: false

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - OpenOrchestraBackofficeBundle
        - OpenOrchestraMediaAdminBundle
        - OpenOrchestraDisplayBundle
        - OpenOrchestraUserBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine_mongodb:
    connections:
        default:
            server: "%open_orchestra_cms.mongodb.server%"
            options: {}
    default_database: "%open_orchestra_cms.mongodb.database%"
    resolve_target_documents:
        OpenOrchestra\ModelInterface\Model\TranslatedValueInterface: OpenOrchestra\ModelBundle\Document\TranslatedValue
        OpenOrchestra\ModelInterface\Model\ReadSiteInterface: OpenOrchestra\ModelBundle\Document\Site
        FOS\UserBundle\Model\GroupInterface: OpenOrchestra\GroupBundle\Document\Group
        Symfony\Component\Security\Core\User\UserInterface: OpenOrchestra\UserBundle\Document\User
        OpenOrchestra\UserBundle\Model\ApiClientInterface: OpenOrchestra\UserBundle\Document\ApiClient
        OpenOrchestra\WorkflowFunction\Model\WorkflowFunctionInterface: OpenOrchestra\WorkflowFunctionBundle\Document\WorkflowFunction
        OpenOrchestra\UserBundle\Model\AuthorizationInterface: OpenOrchestra\UserBundle\Document\Authorization
        OpenOrchestra\ModelInterface\Model\EmbedStatusInterface: OpenOrchestra\ModelBundle\Document\EmbedStatus
        OpenOrchestra\ModelInterface\Model\RoleInterface: OpenOrchestra\ModelBundle\Document\Role
        OpenOrchestra\ModelInterface\Model\AreaInterface: OpenOrchestra\ModelBundle\Document\Area
        OpenOrchestra\ModelInterface\Model\BlockInterface: OpenOrchestra\ModelBundle\Document\Block
        OpenOrchestra\ModelInterface\Model\StatusInterface: OpenOrchestra\ModelBundle\Document\Status
        OpenOrchestra\ModelInterface\Model\ThemeInterface: OpenOrchestra\ModelBundle\Document\Theme
        OpenOrchestra\ModelInterface\Model\SiteAliasInterface: OpenOrchestra\ModelBundle\Document\SiteAlias
        OpenOrchestra\ModelInterface\Model\ContentAttributeInterface: OpenOrchestra\ModelBundle\Document\ContentAttribute
        OpenOrchestra\ModelInterface\Model\FieldTypeInterface: OpenOrchestra\ModelBundle\Document\FieldType
        OpenOrchestra\ModelInterface\Model\FieldOptionInterface: OpenOrchestra\ModelBundle\Document\FieldOption
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: OpenOrchestra\UserBundle\Document\User
    group:
        group_class: OpenOrchestra\GroupBundle\Document\Group

stof_doctrine_extensions:
    mongodb:
        default:
            blameable: true
            timestampable: true

open_orchestra_base:
    encryption_key: %encryption_key%

knp_gaufrette:
    adapters:
        media_storage:
            local:
                directory: %media.directory%
                create: true
    filesystems:
        media_storage:
            adapter: media_storage
            alias: media_storage_filesystem

fos_http_cache:
    proxy_client:
        varnish:
            servers: "%fos_http_cache.proxy_client.varnish.servers%"
            base_url: "%fos_http_cache.proxy_client.varnish.base_url%"
        default: varnish

