imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: log.yml }

framework:
    esi       : { enabled: true }
    translator: { fallback: "%default_locale%" }
    secret    : "%secret%"
    router    :
        resource           : "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form           : ~
    csrf_protection: ~
    validation     : { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: 1.0.0
    default_locale :  "%default_locale%"
    trusted_hosts  :   ~
    trusted_proxies: ~
    session:
        handler_id: ~
        name      : '%session_name%'
    fragments           : { path: /_fragment }
    http_method_override: true

twig:
    debug           : "%kernel.debug%"
    strict_variables: "%kernel.debug%"

braincrafted_bootstrap:
    auto_configure:
        assetic      : false
        knp_menu     : false
        knp_paginator: false
        twig         : false

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags :
           - { name: twig.extension }

doctrine_mongodb:
    connections:
        default:
            server : "%open_orchestra_cms.mongodb.server%"
            options: {}
    default_database        : "%open_orchestra_cms.mongodb.database%"
    resolve_target_documents:
        FOS\UserBundle\Model\GroupInterface: OpenOrchestra\GroupBundle\Document\Group
    document_managers:
        default:
            auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host     : "%mailer_host%"
    username : "%mailer_user%"
    password : "%mailer_password%"

fos_user:
    db_driver    : mongodb
    firewall_name: main
    user_class   : OpenOrchestra\UserBundle\Document\User
    from_email   :
      address: '%from_email_adresse%'
      sender_name: '%from_email_sender_name%'
    group        :
        group_class: OpenOrchestra\GroupBundle\Document\Group

stof_doctrine_extensions:
    mongodb:
        default:
            blameable    : true
            timestampable: true

open_orchestra_base:
    encryption_key: '%encryption_key%'

knp_gaufrette:
    adapters:
        media_storage:
            local:
                directory: '%media.directory%'
                create   : true
    filesystems:
        media_storage:
            adapter: media_storage
            alias  : media_storage_filesystem

fos_http_cache:
    proxy_client:
        varnish:
            servers : '%fos_http_cache.proxy_client.varnish.servers%'
            base_url: '%fos_http_cache.proxy_client.varnish.base_url%'
        default: varnish

open_orchestra_media:
    media_domain: '%media_domain%'

open_orchestra_elastica:
    host: '%host_elastica%'

mongo_db_migrations:
     collection_name: "migration_versions"
     database_name  : "%open_orchestra_cms.mongodb.database%"
     dir_name       : "%kernel.root_dir%/../vendor/open-orchestra/open-orchestra-migration-bundle/MigrationBundle/Migrations"
     script_dir_name: "%kernel.root_dir%/scripts"
     name           : "Open Orchestra MongoDB Migrations"
     namespace      : OpenOrchestra\MigrationBundle\Migrations

bazinga_js_translation:
    active_domains:
        - interface
        - datatable
