monolog:
    handlers:
        main:
            type: stream
            level: 200
            channels: openorchestra
            handler: mongo
        mongo:
            type: mongo
            level: 200
            mongo:
                host: '%open_orchestra_cms.mongodb.host%'
                port: '%open_orchestra_cms.mongodb.port%'
                database: '%open_orchestra_cms.mongodb.database%'
                collection: log
            channels: [openorchestra]
