open_orchestra_backoffice:
    resource: "@OpenOrchestraBackofficeBundle/Controller"
    type: annotation
    prefix: /admin
    options:
        expose: true

open_orchestra_user_admin:
    resource: "@OpenOrchestraUserAdminBundle/Controller/Admin"
    type: annotation
    prefix: /admin
    options:
        expose: true

open_orchestra_media_admin:
    resource: "@OpenOrchestraMediaAdminBundle/Controller/Admin"
    type: annotation
    prefix: /admin

open_orchestra_workflow_admin:
    resource: "@OpenOrchestraWorkflowAdminBundle/Controller/Admin"
    type: annotation
    prefix: /admin

open_orchestra_api_oauth2:
    resource: "@OpenOrchestraBaseApiBundle/Resources/config/oauth2_routing.yml"

open_orchestra_group_admin:
    resource: "@OpenOrchestraGroupBundle/Controller/Admin"
    type: annotation
    prefix: /admin
    options:
        expose: true

open_orchestra_api:
    resource: "@OpenOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_user_api:
    resource: "@OpenOrchestraUserAdminBundle/Controller/Api"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_media_api:
    resource: "@OpenOrchestraMediaAdminBundle/Controller/Api"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_workflow_api:
    resource: "@OpenOrchestraWorkflowAdminBundle/Controller/Api"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_group_api:
    resource: "@OpenOrchestraGroupBundle/Controller/Api"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_log:
    resource: "@OpenOrchestraLogBundle/Controller"
    type: annotation
    prefix: /api
    options:
        expose: true

open_orchestra_media_file:
    resource: "@OpenOrchestraMediaFileBundle/Controller"
    type: annotation
    prefix: /media
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    options:
        expose: true

root:
    path: /
    methods: ['GET']
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

open_orchestra_base:
    resource: "@OpenOrchestraBaseBundle/Resources/config/routing.yml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
