open_orchestra_backoffice:
    resource: "@OpenOrchestraBackofficeBundle/Controller"
    type: annotation
    prefix: /admin

open_orchestra_user_admin:
    resource: "@OpenOrchestraUserAdminBundle/Controller/Admin"
    type: annotation
    prefix: /admin

#open_orchestra_media_admin:
#    resource: "@OpenOrchestraMediaAdminBundle/Controller/Admin"
#    type: annotation
#    prefix: /admin

open_orchestra_workflow_admin:
    resource: "@OpenOrchestraWorkflowFunctionAdminBundle/Controller/Admin"
    type: annotation
    prefix: /admin

open_orchestra_api_oauth2:
    resource: "@OpenOrchestraBaseApiBundle/Resources/config/oauth2routing.yml"

open_orchestra_api:
    resource: "@OpenOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api

open_orchestra_user_api:
    resource: "@OpenOrchestraUserAdminBundle/Controller/Api"
    type: annotation
    prefix: /api

#open_orchestra_media_api:
#    resource: "@OpenOrchestraMediaAdminBundle/Controller/Api"
#    type: annotation
#    prefix: /api

open_orchestra_workflow_api:
    resource: "@OpenOrchestraWorkflowFunctionAdminBundle/Controller/Api"
    type: annotation
    prefix: /api

open_orchestra_log:
    resource: "@OpenOrchestraLogBundle/Controller"
    type: annotation
    prefix: /api

#open_orchestra_media:
#    resource: "@OpenOrchestraMediaBundle/Controller"
#    type: annotation
#    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root:
    path: /
    methods: ['GET']
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

open_orchestra_base:
    resource: "@OpenOrchestraBaseBundle/Resources/config/routing.yml"
