parameters:
    php_orchestra_cms.languages.availables :
        - en
        - fr
        - de
        - es
    kernel.default_locale : en
    
lexik_translation:
    fallback_locale: "%kernel.default_locale%"
    managed_locales: "%php_orchestra_cms.languages.availables%"
    base_layout: "PHPOrchestraCMSBundle:BackOffice:Translation/layout.html.twig"
    #use_yml_tree: false
    #grid_input_type: text
    storage:
        type: mongodb
        object_manager: default
    #resources_registration:
    #    type: all
    #    managed_locales_only: true

framework:
    translator: { fallback: "%kernel.default_locale%" }

twig:
    form:
        resources:
            - 'PHPOrchestraCMSBundle:Form:contentTypeFields.html.twig'
    globals:
        available_languages: %php_orchestra_cms.languages.availables%
        context: @php_orchestra_cms.context_manager

php_orchestra_theme:
    themes: 
        sample:
            name: "Native example"
            stylesheets:
                - PHPOrchestraThemeBundle:sample:css/div.css
                - PHPOrchestraThemeBundle:sample:css/font.css
        theme1:
            name: "Theme \#1"
            stylesheets :
                - FakeAppThemeBundle:theme1:css/font.css
                - FakeAppThemeBundle:theme1:css/color.css
                - FakeAppThemeBundle:theme1:css/bg.css
            javascripts :
                - PHPOrchestraThemeBundle:theme1:js/alert.js
        theme2:
            name: "Theme \#2"
            stylesheets :
                - FakeAppThemeBundle:theme2:css/another.css
                - FakeAppThemeBundle:theme2:css/custom.css
                - FakeAppThemeBundle:theme2:css/master.css
        fromApp:
            name: "Theme from app"
            stylesheets :
                - FakeAppThemeBundle:fromApp:css/master.css
            javascripts :
                - FakeAppThemeBundle:fromApp:js/js.js
                - FakeAppThemeBundle:fromApp:js/subfolder/sub.js
        mixed:
            name: "Theme mixing several other themes"
            stylesheets :
                - PHPOrchestraThemeBundle:sample:css/fo.css
                - FakeAppThemeBundle:theme2:css/main.css
            javascripts :
                - PHPOrchestraThemeBundle:theme1:js/empty.js
                - FakeAppThemeBundle:fromApp:js/subfolder/sub.js
